version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/work
      - vendor-store:/work/vendor
      - node_modules-store:/work/node_modules
      - storage-store:/work/storage

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./src:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - storage-store:/work/storage
      - ./src/storage:/work/hoge
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  vendor-store:
  node_modules-store:
  storage-store:
